## Numpy and Basics

In [1]:
import numpy as np

### creating array from list

In [3]:
arr_1d=np.array([1,2,3,4,5])
print(arr_1d)

arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### lists vs numpy

In [6]:
py_list=[1,2,3]
print("Python list multiplication: ",py_list*2)

np_array=np.array([1,2,3]) #element wise multiplication
print("Python array multiplication: ",np_array*2)

import time

start=time.time()

py_list=[i*2 for i in range(1000000)]
print("\n List operation time: ",time.time()-start)

start=time.time()

np_array=np.arange(1000000)*2
print("\n Numpy operation time: ",time.time()-start)


Python list multiplication:  [1, 2, 3, 1, 2, 3]
Python array multiplication:  [2 4 6]

 List operation time:  0.09585690498352051

 Numpy operation time:  0.008009195327758789


### creating array from scratch

In [14]:
zeros=np.zeros((3,4))
print("zeros array: \n",zeros)

ones=np.ones((2,3))
print("ones array: \n",ones)

full=np.full((2,2),7)
print("full array: \n",full)

random=np.random.random((2,3))
print("random array: \n",random)

sequence=np.arange(0,10,2)
print("sequence array: \n",sequence)


zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.79128729 0.58528073 0.1549125 ]
 [0.30960628 0.05697088 0.80640247]]
sequence array: 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [17]:
vector=np.array([1,2,3])
print("Vector: ",vector)

matrix=np.array([[1,2,3],[4,5,6]])
print("Matrix: ",matrix)

tensor=np.array([[[1,2],[3,4]],
                 [[5,6],[7,8]]])
print("Tensor: ",tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [18]:
arr=np.array([[1,2,3],[4,5,6]])

print("Shape ",arr.shape)
print("Dimension ",arr.ndim)
print("Size ",arr.size)
print("DType ",arr.dtype)

Shape  (2, 3)
Dimension  2
Size  6
DType  int64


### Array Reshaping

In [23]:
arr=np.arange(12)
print("Original Array ",arr)

reshaped=arr.reshape((3,4))
print("\nReshaped array ",reshaped)

flattened=reshaped.flatten()
print("\n Flattened Array ",flattened)

#ravel (returns view,instead of copy)
raveled=reshaped.ravel()
print("\n Raveled Array ",raveled)

#transpose

transpose=reshaped.T
print("\n Transposed Array ",transpose)


Original Array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened Array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled Array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed Array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
