## Numpy and Basics

In [2]:
import numpy as np

### creating array from list

In [3]:
arr_1d=np.array([1,2,3,4,5])
print(arr_1d)

arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### lists vs numpy

In [6]:
py_list=[1,2,3]
print("Python list multiplication: ",py_list*2)

np_array=np.array([1,2,3]) #element wise multiplication
print("Python array multiplication: ",np_array*2)

import time

start=time.time()

py_list=[i*2 for i in range(1000000)]
print("\n List operation time: ",time.time()-start)

start=time.time()

np_array=np.arange(1000000)*2
print("\n Numpy operation time: ",time.time()-start)


Python list multiplication:  [1, 2, 3, 1, 2, 3]
Python array multiplication:  [2 4 6]

 List operation time:  0.09585690498352051

 Numpy operation time:  0.008009195327758789


### creating array from scratch

In [14]:
zeros=np.zeros((3,4))
print("zeros array: \n",zeros)

ones=np.ones((2,3))
print("ones array: \n",ones)

full=np.full((2,2),7)
print("full array: \n",full)

random=np.random.random((2,3))
print("random array: \n",random)

sequence=np.arange(0,10,2)
print("sequence array: \n",sequence)


zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.79128729 0.58528073 0.1549125 ]
 [0.30960628 0.05697088 0.80640247]]
sequence array: 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [17]:
vector=np.array([1,2,3])
print("Vector: ",vector)

matrix=np.array([[1,2,3],[4,5,6]])
print("Matrix: ",matrix)

tensor=np.array([[[1,2],[3,4]],
                 [[5,6],[7,8]]])
print("Tensor: ",tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [18]:
arr=np.array([[1,2,3],[4,5,6]])

print("Shape ",arr.shape)
print("Dimension ",arr.ndim)
print("Size ",arr.size)
print("DType ",arr.dtype)

Shape  (2, 3)
Dimension  2
Size  6
DType  int64


### Array Reshaping

In [23]:
arr=np.arange(12)
print("Original Array ",arr)

reshaped=arr.reshape((3,4))
print("\nReshaped array ",reshaped)

flattened=reshaped.flatten()
print("\n Flattened Array ",flattened)

#ravel (returns view,instead of copy)
raveled=reshaped.ravel()
print("\n Raveled Array ",raveled)

#transpose

transpose=reshaped.T
print("\n Transposed Array ",transpose)


Original Array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened Array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled Array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed Array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### Random Number generation in Numpy

In [ ]:
# 1-d array of random numbers
data=np.random.random(20)
print(data)

[0.59880767 0.59429043 0.14124557 0.42194125 0.56400829 0.24757041
 0.36502926 0.78810921 0.49476311 0.45098304 0.61152622 0.91392479
 0.53577477 0.65949802 0.16667481 0.42162901 0.79165358 0.2894934
 0.1194419  0.23729834]


In [6]:
#2d array of random numbers

data_2d=np.random.random((2,3))
print(data_2d)

[[0.42981476 0.45458072 0.69089956]
 [0.62930572 0.99364312 0.87557653]]


#### Using Rand()

In [8]:
#2-d array using rand function

d2_rand=np.random.rand(2,3)
print(d2_rand)

[[0.12364624 0.81933125 0.96710731]
 [0.38928311 0.87486532 0.96659833]]


#### Using Randn()


In [9]:
d2_randn=np.random.randn(2,3)
print(d2_randn)

[[-0.43062662  0.53629255 -0.07519562]
 [ 1.25571435  2.10195091  0.67794903]]


### NOTE
* Both random() and rand() functions generate samples from the uniform distribution on [0, 1).
* randn() generates samples from normal distribution.

In [11]:
randint_data=np.random.randint(-10,20,5)
print(randint_data)

randint_data_2d=np.random.randint(-10,20,(2,3))
print(randint_data_2d)

[-1 16 -7 14  1]
[[ 6 -5  7]
 [ 1 16  2]]


In [12]:
zeroes_4x5=np.zeros((4,5))
print(zeroes_4x5)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
ones_3x6=np.ones((3,6))
print(ones_3x6)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [14]:
random_2x10=np.random.random((2,10))
print(random_2x10)

[[0.91212875 0.8599701  0.63448733 0.95409666 0.00557756 0.62305752
  0.77012448 0.61748018 0.50581863 0.7336363 ]
 [0.91919813 0.98578907 0.36580552 0.00691672 0.6343343  0.02625088
  0.51144271 0.30606992 0.12417667 0.07847391]]


In [15]:
randint_6x3=np.random.randint(230,500,(6,3))
print(randint_6x3)

[[388 345 483]
 [329 494 498]
 [455 284 230]
 [432 332 442]
 [474 468 276]
 [456 273 497]]


Creating numpy array using arange()

In [17]:
print(np.arange(1,10))
print(np.arange(1,10,2))

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [18]:
full_method=np.full((2,3),5)
print(full_method)

[[5 5 5]
 [5 5 5]]


create identity matrix

In [20]:
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [24]:
equal_space_ar=np.arange(1,100,26)
print(equal_space_ar)

range_50_150=np.arange(50,150,3)
print(range_50_150)

print(np.full((5,5),fill_value=27))

print(np.identity(3))

[ 1 27 53 79]
[ 50  53  56  59  62  65  68  71  74  77  80  83  86  89  92  95  98 101
 104 107 110 113 116 119 122 125 128 131 134 137 140 143 146 149]
[[27 27 27 27 27]
 [27 27 27 27 27]
 [27 27 27 27 27]
 [27 27 27 27 27]
 [27 27 27 27 27]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Linear Algebra

In [27]:
mat=np.array([[1,2],[3,4]])
det=np.linalg.det(mat)

print(f"Determinant of the matrix: {det}")

inv=np.linalg.inv(mat)
print(inv)

eign=np.linalg.eig(mat)
print(eign)

Determinant of the matrix: -2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [28]:
"""
Given a square matrix, check if it's invertible by computing its determinant.
If invertible, compute its inverse.

Task: Generate a random 3x3 matrix, check determinant, and if nonzero,
compute inverse.
"""

mat_3X3=np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
det_mat=np.linalg.det(mat_3X3)
inverse=None

if det!=0:
    inverse=np.linalg.inv(mat_3X3)
print(det_mat)
print(inverse)

0.9999999999999964
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [30]:
"""
# Create an array:
# arr = [10, 20, 30, 40, 50, 60]

# a) Select all elements greater than 30.
# b) Select all even elements.
"""

arr = np.array([10,20,30,40,50,60])
print(arr[arr>30])
print(arr[arr%2==0])

[40 50 60]
[10 20 30 40 50 60]


In [31]:
"""
Given a Ax = B, solve using np.linalg.solve(). Then verify if it is correct.
"""
A = np.array([[2, 1], [1, 3]])
b = np.array([7, 10])
x = np.linalg.solve(A, b)
print(x)
print(np.dot(A, x))
# The below function checks if the results are close
print(np.allclose(np.dot(A, x), b))

[2.2 2.6]
[ 7. 10.]
True
